# Terraform Drift Fixes
# Generated by Terraform Drift Detector
# Generated at: 2026-01-05 12:00:25.958429

# INSTRUCTIONS:
# 1. Review each resource below
# 2. Update your actual .tf files with the changes
# 3. Run 'terraform plan' to verify
# 4. Run 'terraform apply' to fix drift

# ======================================================================

# Resource: aws_instance.test
# Severity: HIGH
# Issue: 3 attribute(s) drifted

resource "aws_instance" "test" {
  instance_type = "t2.small"  # Changed from "t2.micro"
  # public_ip changed: "65.2.189.96" -> "13.232.174.11"
  # state changed: "None" -> "running"
}

# Note: Update your actual .tf file with values from AWS (shown above)
# Or run "terraform apply" to revert AWS to match your Terraform state

# Manual steps:
# 1. Review the drifted attributes below
# 2. Update your .tf file with the suggested changes
# 3. Run: terraform plan (to verify changes)
# 4. Run: terraform apply (to fix drift)

# ----------------------------------------------------------------------

